### ISSUE TITLE
Segfault when using withCtx or verifyPlain'

### ISSUE THREAD

**Issue by Ulrar** [rethab/h-gpgme#43] opened 2018-02-22 07:44 UTC
Hi,

As mentioned there : https://stackoverflow.com/questions/48908274/using-crypto-gpgme-to-check-signatures

It looks like using withCtx (or verifyplain') to check on a signature causes a segfault. Using newCtx and freeing it later does work fine (well ish, see stackoverflow for what looks like another bug), so I assume the Ctx is accessed outside of verifyPlain for some reason.

```haskell
parseData signedData = do
  res <- liftIO $ verifyPlain' "gpghome" (DBL.toStrict signedData) ""
  case res of
    Left err -> return $ Left $ errorString err
    Right ((err, _, fg):xs, msg) -> case errorString err of
      "Success" -> return $ Right (fg, msg)
      _         -> return $ Left $ errorString err

parseRequest d = do
  parsed <- parseData d
  case parsed of
    Left err        -> throw $ UnknownError err
    Right (fg, msg) -> return (fg, msg)
```

**Comment by rethab** [comment] 2018-02-22 08:23
hi @Ulrar thanks for reporting. Would you mind creating a small PR with a test that fails because of this issue? Unfortunately, my time is limited and providing such a small reproducer that can also be used as regression test would be greatly welcome.

- Reto

**Comment by rethab** [comment] 2018-04-08 16:42
I have tried this test and it does not segfault:

```haskell
verify_segfault :: Assertion
verify_segfault = do
  resSign  <- withCtx "test/bob/" "C" OpenPGP $ \ctx -> do
    sign ctx [] Normal "Normal text message from bob with default key"
  resVerify <- verify' "test/bob/" (fromRight resSign)
  assertBool "Could not verify bob's signature was correct" $ isVerifyValid resVerify
```

I'm closing this issue. Feel free to open with a reproducing snippet.

**Closed by rethab** 2018-04-08 16:42 UTC
Labels: bug, help wanted, needs verification
